import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import InsightsTableDescription from './InsightsTableDescription';

// Mock MUI icons
vi.mock('@mui/icons-material', () => ({
  AssistantOutlined: () => <div data-testid="assistant-icon">AssistantOutlined</div>,
  HelpOutline: () => <div data-testid="help-icon">HelpOutline</div>,
}));

describe('InsightsTableDescription', () => {
  const defaultProps = {
    description: 'This is a test table description generated by AI.',
    onViewColumnDescriptions: vi.fn(),
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // ==========================================================================
  // Rendering Tests
  // ==========================================================================

  describe('Rendering', () => {
    it('renders with section title "Table Description"', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      expect(screen.getByText('Table Description')).toBeInTheDocument();
    });

    it('renders the assistant (AI) icon', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      expect(screen.getByTestId('assistant-icon')).toBeInTheDocument();
    });

    it('renders help tooltip icon', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      expect(screen.getByTestId('help-icon')).toBeInTheDocument();
    });

    it('renders description text', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      expect(screen.getByText(defaultProps.description)).toBeInTheDocument();
    });

    it('renders "View column descriptions" link', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      expect(screen.getByText('View column descriptions')).toBeInTheDocument();
    });

    it('shows description content by default', () => {
      render(<InsightsTableDescription {...defaultProps} />);

      // Description should be visible
      expect(screen.getByText(defaultProps.description)).toBeVisible();
    });
  });

  // ==========================================================================
  // View Column Descriptions Tests
  // ==========================================================================

  describe('View Column Descriptions', () => {
    it('calls onViewColumnDescriptions when link clicked', async () => {
      const user = userEvent.setup();
      const mockOnViewColumnDescriptions = vi.fn();

      render(
        <InsightsTableDescription
          {...defaultProps}
          onViewColumnDescriptions={mockOnViewColumnDescriptions}
        />
      );

      const link = screen.getByText('View column descriptions');
      await user.click(link);

      expect(mockOnViewColumnDescriptions).toHaveBeenCalledTimes(1);
    });

    it('keeps description content visible after link clicked', async () => {
      const user = userEvent.setup();
      render(<InsightsTableDescription {...defaultProps} />);

      const link = screen.getByText('View column descriptions');
      await user.click(link);

      // Content should still be visible
      expect(screen.getByText(defaultProps.description)).toBeVisible();
    });
  });

  // ==========================================================================
  // Edge Cases Tests
  // ==========================================================================

  describe('Edge Cases', () => {
    it('handles empty description', () => {
      render(
        <InsightsTableDescription
          description=""
          onViewColumnDescriptions={defaultProps.onViewColumnDescriptions}
        />
      );

      // Component should still render
      expect(screen.getByText('Table Description')).toBeInTheDocument();
      expect(screen.getByText('View column descriptions')).toBeInTheDocument();
    });

    it('handles very long description', () => {
      const longDescription = 'A'.repeat(1000);

      render(
        <InsightsTableDescription
          description={longDescription}
          onViewColumnDescriptions={defaultProps.onViewColumnDescriptions}
        />
      );

      expect(screen.getByText(longDescription)).toBeInTheDocument();
    });

    it('handles description with special characters', () => {
      const specialDescription = 'Test <script>alert("xss")</script> & "quotes" \'single\'';

      render(
        <InsightsTableDescription
          description={specialDescription}
          onViewColumnDescriptions={defaultProps.onViewColumnDescriptions}
        />
      );

      expect(screen.getByText(specialDescription)).toBeInTheDocument();
    });
  });
});
